[34m[1mwandb[39m[22m:   1 of 1 files downloaded.
[31mERROR[39m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\app\routers\mark.py", line 200, in mark_assessment
    download_artifact()
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\app\ml\predict.py", line 23, in download_artifact
    joblib.dump(model, config.ML_MODEL_PATH)
  File "C:\Users\Chimaobi Okite\Desktop\SmartSchool\.venv\lib\site-packages\joblib\numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Chimaobi Okite\\Desktop\\SmartSchool\\app\\ml/models\\models\\lgbm_class.model.pkl'
.\artifacts\LBGMClassifier-v14\lgbm_class.model.pkl
.\artifacts\LBGMClassifier-v14
